language: cpp

matrix:
  include:
    # - os: linux
    #   compiler: clang
    #   addons: &clang38
    #     apt:
    #       sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
    #       packages: ['clang-3.8']
    #   env: COMPILER='clang++-3.8' BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER='g++-5'

    # - os: osx
    #   osx_image: xcode7
    #   compiler: clang
    #   env: COMPILER='ccache clang++' BUILD_TYPE='Release'

before_install:
  - uname -a

install:
  - curl -sL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz
  - export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH
  - mkdir vendor/build
  - cd vendor/build
  - export CC="gcc-5"
  - export CXX="g++-5"
  - cmake .. -DVENDOR_PLATFORM=linux-x64-gcc
  - make
  - make install

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
